# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1182, 896)
        Form.setMinimumSize(QtCore.QSize(1182, 896))
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setGeometry(QtCore.QRect(11, 434, 93, 28))
        self.btn.setObjectName("btn")
        self.light = QtWidgets.QPushButton(Form)
        self.light.setGeometry(QtCore.QRect(460, 240, 50, 50))
        self.light.setStyleSheet("QPushButton\n"
"{border-radius:25px;\n"
"background:rgb(255, 0, 0);\n"
"border:8px rgb(255, 254, 253);\n"
"border-style:outset\n"
"}")
        self.light.setText("")
        self.light.setObjectName("light")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn.setText(_translate("Form", "start"))
